# Generated by Django 4.2.8 on 2024-11-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0015_library_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='lyrics',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lyrics URL'),
        ),
        migrations.AlterField(
            model_name='library',
            name='media',
            field=models.URLField(max_length=500, verbose_name='Media URL'),
        ),
    ]
